### ISSUE TITLE
What version of macOS is supported？

### ISSUE THREAD

**Issue by Lstink** [startpenghubingzhou/Xiaoxin-Chao-7000-Hackintosh-OC#1]
What version of macOS is supported？

**Comment by godcheese** [comment]
macOS 10.15+

**Comment by startpenghubingzhou** [comment]
请先确认你的机型是小新潮7000，非小新潮7000机型不支持。
此efi只适用于10.15.6以下版本。

Pls ensure that  your laptop is Lenovo Xiaoxin Chao 7000, and other laptops are not supported.
This EFI can only be used under macos 10.15.6.
